export const TOGGLE_FAVORITES = 'TOGGLE_FAVORITES';
export const SET_FAVORITES = 'SET_FAVORITES';
export const UPDATE_BEERS = 'UPDATE_BEERS';
export const LOAD_ALL_DATA = 'LOAD_ALL_DATA';
export const UPDATE_FAVORITE_BEERS = 'UPDATE_FAVORITE_BEERS';
export const SET_BEER = 'SET_BEER';
export const INCREASE_PAGE_COUNT = 'INCREASE_PAGE_COUNT';
export const REPLACE_BEERS = 'REPLACE_BEERS';
