export const TOGGLE_FAVORITES = 'TOGGLE_FAVORITES';
export const SET_FAVORITES = 'SET_FAVORITES';
export const UPDATE_BEERS = 'UPDATE_BEERS';
export const UPDATE_FAVORITE_BEERS = 'UPDATE_FAVORITE_BEERS';
